# Problem: Find the Difference
# Platform: LeetCode
# Difficulty: Easy
# Topic: Hashtable,Strings,Bit Manipulation,Sorting
# Language: Python

#  Problem Description:
# You are given two strings s and t.

#String t is generated by random shuffling string s and then add one more letter at a random position.

#Return the letter that was added to t.

#  Approach:
# Loop through each character in t.
#Compare how many times that character appears in t and s.
#The character whose frequency is different is the extra character added in t, so return it.

#  Time Complexity: O(n²)
#  Space Complexity: O(1)
class Solution(object):
    def findTheDifference(self, s, t):
        for i in t:
            if t.count(i) != s.count(i):
                return i
